var typed = new Typed('.blink', {
  strings: ["NAME :  SANJAY SINGH BISHT^1000","PROFESSION :  FRONT-END-WEB-DESIGN^1000","PASSION :  PROGRAMMING^1000","EXPERIENCE :  6 YEARS","SKILLS SET :  HTML/HTML5^1000","SKILLS SET :  CSS/CSS3^1000","SKILLS SET :  BOOTSTRAP^1000","SKILLS SET :  JAVASCRIPT^1000","SKILLS SET :  JQUERY^1000","SKILLS SET :  SASS WITH FLEXBOX^1000","WITH A LOT OF REAL-LIFE PROJECTS !^1000","COMING SOON WITH PORTFOLIO !^10000"],
  typeSpeed: 50,
    backSpeed: 25,
    smartBackspace: true, 
    cursorChar: '',
    loop: true
});