$(()=>{
    $(".b").mouseover(()=>{
        $(".b").css({"background-color":"transparent"});
    });
     $(".b").mouseout(()=>{
        $(".b").css({"background-color":"#c00101"});
    });
    $(".k").mouseover(()=>{
        $(".k").css({"background-color":"#c00101"});
    });
     $(".k").mouseout(()=>{
        $(".k").css({"background-color":"transparent"});
    });
    $(".kb").mouseover(()=>{
        $(".kb").css({"background-color":"white",
                     "color":"#c00101"});
    });
     $(".kb").mouseout(()=>{
        $(".kb").css({"background-color":"#c00101",
                     "color":"white"});
    });
    $(".nl1").mouseover(()=>{
        $(".nl1").css("color","#c00101");
    });
     $(".nl1").mouseout(()=>{
        $(".nl1").css("color","white");
    });
     $(".nl2").mouseover(()=>{
        $(".nl2").css("color","#c00101");
    });
     $(".nl2").mouseout(()=>{
        $(".nl2").css("color","white");
    });
     $(".nl3").mouseover(()=>{
        $(".nl3").css("color","#c00101");
    });
     $(".nl3").mouseout(()=>{
        $(".nl3").css("color","white");
    });
     $(".nl4").mouseover(()=>{
        $(".nl4").css("color","#c00101");
    });
     $(".nl4").mouseout(()=>{
        $(".nl4").css("color","white");
    });
     $(".nl5").mouseover(()=>{
        $(".nl5").css("color","#c00101");
    });
     $(".nl5").mouseout(()=>{
        $(".nl5").css("color","white");
    });
     $(".nl6").mouseover(()=>{
        $(".nl6").css("color","#c00101");
    });
     $(".nl6").mouseout(()=>{
        $(".nl6").css("color","white");
    });
  $(".bc").mouseover(()=>{
      $(".bc").css("opacity","0.8");
  });
  $(".bc").mouseout(()=>{
      $(".bc").css("opacity","1");
  });  
   $(".mc").mouseover(()=>{
      $(".mc").css({"background-color":"#c00101"});
  });
  $(".mc").mouseout(()=>{
      $(".mc").css({"background-color":"transparent"});
  });
    $(".scb").mouseover(()=>{
      $(".scb").css({"background-color":"#c00101"});
  });
  $(".scb").mouseout(()=>{
      $(".scb").css({"background-color":"transparent"});
  });
    $(".bfc").mouseover(()=>{
      $(".bfc").css({"background-color":"white",
                    "color":"#c00101"});
  });
  $(".bfc").mouseout(()=>{
      $(".bfc").css({"background-color":"#c00101",
                    "color":"white"});
  });
});




